# Generated by Django 3.0.5 on 2020-04-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_userinfos_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
