# Generated by Django 3.0.5 on 2020-04-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200418_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsinfo',
            name='news_essentials',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='动作要领'),
        ),
    ]
