# Generated by Django 3.0.5 on 2020-04-18 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20200416_1533'),
        ('order', '0001_initial'),
        ('good', '0004_auto_20200417_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(blank=True, max_length=500, null=True, verbose_name='评论内容')),
                ('comment_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='good.Good', verbose_name='物品')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='订单')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserAccount', verbose_name='用户账户')),
            ],
        ),
    ]
