# Generated by Django 3.0.5 on 2020-04-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200418_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsinfo',
            name='comment_create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
