# Generated by Django 3.0.5 on 2020-04-16 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20200416_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_status', models.CharField(max_length=10, verbose_name='状态')),
            ],
            options={
                'verbose_name': '商品类型',
                'db_table': 'good_state',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=40, verbose_name='商品名称')),
                ('good_image', models.CharField(max_length=40, verbose_name='商品图片')),
                ('good_content', models.CharField(max_length=40, verbose_name='商品简介')),
                ('good_location', models.CharField(max_length=40, verbose_name='商品位置')),
                ('good_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserAccount', verbose_name='发布者账户')),
                ('good_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='good.GoodType', verbose_name='商品类型')),
            ],
        ),
    ]
