# Generated by Django 3.0.5 on 2020-04-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodtype',
            old_name='good_status',
            new_name='good_type',
        ),
        migrations.AddField(
            model_name='good',
            name='good_number',
            field=models.CharField(default=None, max_length=40, verbose_name='商品编号'),
        ),
        migrations.AlterModelTable(
            name='goodtype',
            table='good_type',
        ),
    ]
