# Generated by Django 3.0.5 on 2020-04-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0002_auto_20200417_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='good_image',
            field=models.CharField(default=None, max_length=40, verbose_name='商品图片'),
        ),
    ]
