# Generated by Django 3.0.5 on 2020-04-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0003_auto_20200417_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='good_content',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='商品简介'),
        ),
        migrations.AlterField(
            model_name='good',
            name='good_image',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='good',
            name='good_location',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='商品位置'),
        ),
        migrations.AlterField(
            model_name='good',
            name='good_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='good',
            name='good_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='商品编号'),
        ),
    ]
