# Generated by Django 3.0.5 on 2020-05-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0005_auto_20200425_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='good_content',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='商品简介'),
        ),
    ]
