# Generated by Django 3.0.5 on 2020-04-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='电话'),
        ),
    ]
