# Generated by Django 3.0.5 on 2020-04-17 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('good', '0004_auto_20200417_1138'),
        ('user', '0002_auto_20200416_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(max_length=10, verbose_name='状态')),
            ],
            options={
                'verbose_name': '订单状态',
                'db_table': 'order_state',
            },
        ),
        migrations.CreateModel(
            name='OrderTimePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time_period', models.CharField(max_length=100, verbose_name='可用时间段')),
            ],
            options={
                'verbose_name': '预约可用时间段',
                'db_table': 'order_time_period',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order_date', models.DateField(verbose_name='预约日期')),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='good.Good', verbose_name='商品ID')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderStatus', verbose_name='订单状态')),
                ('order_time_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderTimePeriod', verbose_name='预约时间段')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserAccount', verbose_name='用户账户')),
            ],
        ),
    ]
