# Generated by Django 3.0.5 on 2020-05-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_order_is_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_is_comment',
            field=models.CharField(blank=True, default='评价一下', max_length=50, null=True, verbose_name='是否已评论'),
        ),
    ]
